create database Grocerydb;
use Grocerydb;

-- 1. Supplier Table
CREATE TABLE IF NOT EXISTS supplier (
 sup_id TINYINT PRIMARY KEY,
 sup_name VARCHAR(255),
 address TEXT
);
-- 2. Categories Table
CREATE TABLE IF NOT EXISTS categories (
 cat_id TINYINT PRIMARY KEY,
 cat_name VARCHAR(255)
);
-- 3. Employees Table
CREATE TABLE IF NOT EXISTS employees (
 emp_id TINYINT PRIMARY KEY,
 emp_name VARCHAR(255),
 hire_date VARCHAR(255)
);
-- 4. Customers Table
CREATE TABLE IF NOT EXISTS customers (
 cust_id SMALLINT PRIMARY KEY,
 cust_name VARCHAR(255),
 address TEXT
);
-- 5. Products Table
CREATE TABLE IF NOT EXISTS products (
 prod_id TINYINT PRIMARY KEY,
 prod_name VARCHAR(255),
 sup_id TINYINT,
 cat_id TINYINT,
 price DECIMAL(10,2),
 FOREIGN KEY (sup_id) REFERENCES supplier(sup_id)
 ON UPDATE CASCADE ON DELETE CASCADE,
 FOREIGN KEY (cat_id) REFERENCES categories(cat_id)
 ON UPDATE CASCADE ON DELETE CASCADE
);
-- 6. Orders Table
CREATE TABLE IF NOT EXISTS orders (
 ord_id SMALLINT PRIMARY KEY,
 cust_id SMALLINT,
 emp_id TINYINT,
 order_date VARCHAR(255),
 FOREIGN KEY (cust_id) REFERENCES customers(cust_id)
 ON UPDATE CASCADE ON DELETE CASCADE,
 FOREIGN KEY (emp_id) REFERENCES employees(emp_id)
 ON UPDATE CASCADE ON DELETE CASCADE
);
-- 7. Order_Details Table
CREATE TABLE IF NOT EXISTS order_details (
 ord_detID SMALLINT AUTO_INCREMENT PRIMARY KEY,
 ord_id SMALLINT,
 prod_id TINYINT,
 quantity TINYINT,
 each_price DECIMAL(10,2),
 total_price DECIMAL(10,2),
 FOREIGN KEY (ord_id) REFERENCES orders(ord_id)
 ON UPDATE CASCADE ON DELETE CASCADE,
 FOREIGN KEY (prod_id) REFERENCES products(prod_id)
 ON UPDATE CASCADE ON DELETE CASCADE
);

-- 1. Customer Insights

-- Question: How many unique customers have placed orders?
SELECT COUNT(DISTINCT cust_id) AS unique_customers
FROM orders;

-- Question: Which customers have placed the highest number of orders?
SELECT 
    c.cust_id,
    c.cust_name,
    COUNT(o.ord_id) AS total_orders
FROM customers c
JOIN orders o 
    ON c.cust_id = o.cust_id
GROUP BY c.cust_id, c.cust_name
ORDER BY total_orders DESC;

-- Question: What is the total and average purchase value per customer?
SELECT 
    c.cust_id,
    c.cust_name,
    SUM(od.total_price) AS total_purchase_value,
    AVG(od.total_price) AS average_purchase_value
FROM customers c
JOIN orders o 
    ON c.cust_id = o.cust_id
JOIN order_details od 
    ON o.ord_id = od.ord_id
GROUP BY c.cust_id, c.cust_name
ORDER BY total_purchase_value DESC;

-- Question: Who are the top 5 customers by total purchase amount?
SELECT 
    c.cust_id,
    c.cust_name,
    SUM(od.total_price) AS total_purchase_amount
FROM customers c
JOIN orders o 
    ON c.cust_id = o.cust_id
JOIN order_details od 
    ON o.ord_id = od.ord_id
GROUP BY c.cust_id, c.cust_name
ORDER BY total_purchase_amount DESC
LIMIT 5;

-- 2. Product Performance

-- Question: How many products exist in each category?
SELECT 
    c.cat_id,
    c.cat_name,
    COUNT(p.prod_id) AS total_products
FROM categories c
LEFT JOIN products p 
    ON c.cat_id = p.cat_id
GROUP BY c.cat_id, c.cat_name
ORDER BY total_products DESC;

-- Question: What is the average price of products by category?
SELECT 
    c.cat_id,
    c.cat_name,
    AVG(p.price) AS average_product_price
FROM categories c
JOIN products p 
    ON c.cat_id = p.cat_id
GROUP BY c.cat_id, c.cat_name
ORDER BY average_product_price DESC;

-- Question: Which products have the highest total sales volume (by quantity)?
SELECT 
    p.prod_id,
    p.prod_name,
    SUM(od.quantity) AS total_sales_volume
FROM products p
JOIN order_details od 
    ON p.prod_id = od.prod_id
GROUP BY p.prod_id, p.prod_name
ORDER BY total_sales_volume DESC;

-- Question: What is the total revenue generated by each product?
SELECT 
    p.prod_id,
    p.prod_name,
    SUM(od.total_price) AS total_revenue
FROM products p
JOIN order_details od 
    ON p.prod_id = od.prod_id
GROUP BY p.prod_id, p.prod_name
ORDER BY total_revenue DESC;

-- Question: How do product sales vary by category and supplier?
SELECT 
    c.cat_name,
    s.sup_name,
    SUM(od.quantity) AS total_quantity_sold,
    SUM(od.total_price) AS total_sales_revenue
FROM order_details od
JOIN products p 
    ON od.prod_id = p.prod_id
JOIN categories c 
    ON p.cat_id = c.cat_id
JOIN supplier s 
    ON p.sup_id = s.sup_id
GROUP BY c.cat_name, s.sup_name
ORDER BY total_sales_revenue DESC;

-- 3. Sales and Order Trends

-- Question: How many orders have been placed in total?
SELECT COUNT(*) AS total_orders
FROM orders;

-- Question: What is the average value per order?
SELECT 
    AVG(order_total) AS average_order_value
FROM (
    SELECT 
        ord_id,
        SUM(total_price) AS order_total
    FROM order_details
    GROUP BY ord_id
) AS order_summary;

-- Question: On which dates were the most orders placed?
SELECT 
    order_date,
    COUNT(ord_id) AS total_orders
FROM orders
GROUP BY order_date
ORDER BY total_orders DESC;

-- Question: What are the monthly trends in order volume and revenue?
SELECT 
    MONTH(STR_TO_DATE(order_date, '%Y-%m-%d')) AS month_number,
    COUNT(DISTINCT o.ord_id) AS total_orders,
    SUM(od.total_price) AS total_revenue
FROM orders o
JOIN order_details od 
    ON o.ord_id = od.ord_id
GROUP BY month_number
ORDER BY month_number;

-- Question: How do order patterns vary across weekdays and weekends?
SELECT 
    CASE 
        WHEN DAYOFWEEK(STR_TO_DATE(order_date, '%Y-%m-%d')) IN (1,7)
        THEN 'Weekend'
        ELSE 'Weekday'
    END AS day_type,
    COUNT(ord_id) AS total_orders
FROM orders
GROUP BY day_type;

-- 4. Supplier Contribution

-- Question: How many suppliers are there in the database?
SELECT COUNT(*) AS total_suppliers
FROM supplier;

-- Question: Which supplier provides the most products?
SELECT 
    s.sup_id,
    s.sup_name,
    COUNT(p.prod_id) AS total_products
FROM supplier s
JOIN products p 
    ON s.sup_id = p.sup_id
GROUP BY s.sup_id, s.sup_name
ORDER BY total_products DESC;

-- Question: What is the average price of products from each supplier?
SELECT 
    s.sup_id,
    s.sup_name,
    AVG(p.price) AS average_product_price
FROM supplier s
JOIN products p 
    ON s.sup_id = p.sup_id
GROUP BY s.sup_id, s.sup_name
ORDER BY average_product_price DESC;

-- Question: Which suppliers contribute the most to total product sales (by revenue)?
SELECT 
    s.sup_id,
    s.sup_name,
    SUM(od.total_price) AS total_sales_revenue
FROM supplier s
JOIN products p 
    ON s.sup_id = p.sup_id
JOIN order_details od 
    ON p.prod_id = od.prod_id
GROUP BY s.sup_id, s.sup_name
ORDER BY total_sales_revenue DESC;

-- 5. Employee Performance

-- Question: How many employees have processed orders?
SELECT COUNT(DISTINCT emp_id) AS employees_processed_orders
FROM orders;

-- Question: Which employees have handled the most orders?
SELECT 
    e.emp_id,
    e.emp_name,
    COUNT(o.ord_id) AS total_orders_handled
FROM employees e
JOIN orders o 
    ON e.emp_id = o.emp_id
GROUP BY e.emp_id, e.emp_name
ORDER BY total_orders_handled DESC;

-- Question: What is the total sales value processed by each employee?
SELECT 
    e.emp_id,
    e.emp_name,
    SUM(od.total_price) AS total_sales_value
FROM employees e
JOIN orders o 
    ON e.emp_id = o.emp_id
JOIN order_details od 
    ON o.ord_id = od.ord_id
GROUP BY e.emp_id, e.emp_name
ORDER BY total_sales_value DESC;

-- Question: What is the average order value handled per employee?
SELECT 
    e.emp_id,
    e.emp_name,
    AVG(order_total) AS average_order_value
FROM employees e
JOIN (
    SELECT 
        o.emp_id,
        o.ord_id,
        SUM(od.total_price) AS order_total
    FROM orders o
    JOIN order_details od 
        ON o.ord_id = od.ord_id
    GROUP BY o.emp_id, o.ord_id
) AS employee_orders
ON e.emp_id = employee_orders.emp_id
GROUP BY e.emp_id, e.emp_name
ORDER BY average_order_value DESC;

-- 6. Order Details Deep Dive

-- Question: What is the relationship between quantity ordered and total price?
SELECT 
    quantity,
    AVG(total_price) AS average_total_price,
    SUM(total_price) AS total_sales
FROM order_details
GROUP BY quantity
ORDER BY quantity;

-- Question: What is the average quantity ordered per product?
SELECT 
    p.prod_id,
    p.prod_name,
    AVG(od.quantity) AS average_quantity_ordered
FROM products p
JOIN order_details od 
    ON p.prod_id = od.prod_id
GROUP BY p.prod_id, p.prod_name
ORDER BY average_quantity_ordered DESC;

-- Question: How does the unit price vary across products and orders?
SELECT 
    p.prod_id,
    p.prod_name,
    od.ord_id,
    od.each_price AS unit_price
FROM products p
JOIN order_details od 
    ON p.prod_id = od.prod_id
ORDER BY p.prod_name, od.ord_id;